-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mer. 12 avr. 2023 à 11:52
-- Version du serveur : 8.0.31
-- Version de PHP : 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `autocompletion`
--

-- --------------------------------------------------------

--
-- Structure de la table `grimpeurs`
--

DROP TABLE IF EXISTS `grimpeurs`;
CREATE TABLE IF NOT EXISTS `grimpeurs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `prenom` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `nom` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `Infos` varchar(2500) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `grimpeurs`
--

INSERT INTO `grimpeurs` (`id`, `prenom`, `nom`, `Infos`) VALUES
(1, 'Patrick', 'Edlinger', 'Longs cheveux blonds, accent chantant, corps de gymnaste et visage d\'ange, il a sorti l\'escalade de son anonymat, devenant l\'une des figures médiatiques des années 1980. Le magazine Paris Match, qui relate ses exploits, le proclame même personnalité préférée des Français. Pionnier de l\'escalade libre, Patrick Edlinger est aussi un virtuose du solo intégral, à l\'image de son ascension de la voie Orange mécanique sans aucun moyen d\'assurage en 1989, pourtant cotée 8a, l\'un des plus hauts degrés de l\'escalade à l\'époque. Le documentariste Jean-Paul Janssen lui a consacré deux courts-métrages devenus mythiques : Opéra vertical (1982) et La vie au bout des doigts (1983).'),
(2, 'Alain', 'Robert', 'Né le 7 août 1962 à Digoin en Saône-et-Loire1, Alain Robert a vécu son enfance à Valence dans la Drôme. Dès l\'adolescence, il admire les exploits des grands alpinistes contemporains (Bonatti, Messner...) et pratique l\'escalade sur les falaises du Vercors et de l’Ardèche. Dès cette époque, il intègre le solo intégral à sa pratique de l\'escalade, à l\'identique des progressions engagées en alpinisme2.\r\n\r\nAu fil des années, il progresse en escalade sportive et en solo intégral, et atteint le niveau 8 dans les années 1990-1992. Ses performances sont très médiatisées et admirées dans le milieu de l\'escalade ; il établit de nombreux records de difficulté en solo intégral.\r\n\r\nIl réalise notamment en solo intégral ; La Nuit du Lézard (8a+) à Buoux en 1991 avec plusieurs mouvements aléatoires, considéré par Alexander Huber comme l\'un des solos les plus difficiles au monde, et l\'enchaînement 8b à Cornas de l’Abominafreux (8a), l’Abomifreux (7c) et l’Abominable Homme des doigts (7b+)2. Il est également très remarqué en 1996 pour le solo intégral de Pol Pot (7c/8a) dans le Verdon, une voie « morpho » à petites prises et adhérences, à 250 mètres du sol, considéré comme « l\'un des solos les plus audacieux de l\'histoire.'),
(3, 'Pierre', 'Allain', 'Né dans la Vienne, élevé à Paris, il découvre l\'alpinisme dans les années 1920 puis l\'escalade tardivement - vers 27 ans - en forêt de Fontainebleau (ci-dessus dans La Porthos, Bas Cuvier). Il devient le chef de file du « groupe de Bleau », des alpinistes parisiens qui, à défaut de s\'entraîner en montagne, grimpent sur les rochers de grès. En 1948, il publie Alpinisme et compétition (republié aux éditions Guérin), un des premiers manuels du genre. Cartésien, doué de ses mains, Pierre Allain est aussi un inventeur. On lui doit le premier chausson d\'escalade, la veste en duvet, le mousqueton, le descendeur... Faute d\'avoir déposé le moindre brevet, la marque P.A. sera largement copiée.'),
(4, 'Georges', 'Livanos', 'Surnommé « le Grec » compte tenu de ses origines familiales, il a passé toute sa vie à Marseille. S\'il pratique aussi l\'alpinisme, il construit sa légende près de chez lui, sur le calcaire des Calanques, où il popularise l\'escalade et ouvre plus de 500 voies, souvent en escalade artificielle, c\'est-à-dire en se hissant non sur la roche mais sur un étrier, grâce à des points de protection insérés dans les aspérités du caillou. Celui qui se considérait comme « un grimpeur du dimanche », car il ne grimpait que les week-ends et pendant ses congés, est pourtant l\'un des ouvreurs les plus prolifiques de l\'histoire.'),
(5, 'Catherine', 'Destivelle', 'Elle émerge lors du premier âge d\'or de la discipline, dans les années 1980, contribuant à l\'avènement de l\'escalade libre. Précoce, talentueuse, elle contribue à féminiser la discipline et devient l\'une des meilleures grimpeuses de la planète en libre et en solo intégral. Elle pratique également l\'escalade sportive et prend part à des compétitions, bien qu\'elle soit signataire du « manifeste des 19 », qui en rejette le principe. Elle se consacre ensuite à l\'alpinisme. Elle est à ce jour la seule femme à avoir gravi la trilogie des grandes faces nord des Alpes, au Cervin, à l\'Eiger et aux Grandes Jorasses.'),
(6, 'François', 'Legrand', 'Fils d\'un guide de haute montagne, François Legrand possède l\'un des plus beaux palmarès de l\'escalade sportive. Ses parents auraient aimé qu\'il devienne alpiniste, lui ne se voyait que grimpeur. Il quitte donc le domicile familial à 18 ans pour vivre plusieurs mois dans une grotte, à Buoux, site célèbre du Vaucluse pour ses voies d\'escalade en falaise. En 1990, il remporte le circuit de la Coupe du monde, dont il deviendra quintuple tenant du titre. Il fut également triple champion du monde de difficulté.'),
(7, 'Josune', 'Bereziartu', 'Josune Bereziartu est une grimpeuse basque née le 19 janvier 1972 à Lazkao dans la province du Guipuscoa en Espagne.\r\nElle est surtout célèbre pour avoir été, dès 2002, la première femme (elles sont trois à l heure actuelle avec Charlotte Durif et Sasha Diguilian) à avoir réussi une voie dans le 9e degré, Bain de Sang 9a/5.14d, à Saint-Loup en Suisse. Débutant très tôt l\'escalade, Josune commence à se faire une première réputation dans le milieu des compétitions officielles. Elle se tourne pourtant progressivement vers la difficulté extrême en falaise, où elle va particulièrement se distinguer.\r\nElle réalise de nombreuses premières. En 1998, elle est la première femme à réussir un 8c : Honky Tonky. En 2000, elle est toujours la première à réussir un 8c+ :Honky Tonky Mix.\r\nEn 2002, elle est la première femme à réussir un 9a : Bain de Sang ouvert par Fred Nicole à Saint-Loup en Suisse. Cette performance attirera quelques contestations dans le milieu de lescalade, certains grimpeurs (notamment Iker Pou) considérant que Bain de Sang est un 9a plutôt \"facile\". Néanmoins, la voie na pas été décotée depuis, et elle reste la première femme à avoir atteint le 9e degré (plus de dix ans après le premier homme, Wolfgang Güllich en 1991).\r\nEn 2004, elle réalise son second 9a : Logical Progression puis en 2005, atteint même un niveau supérieur avec Bimbaluna côté 9a/9a+ en Suisse. Elle devient aussi la première femme à enchaîner une voie cotée 8b+ à vue , c\'est-à-dire lors de sa première tentative): Hidrofobia, la meilleure performance masculine à vue étant 8c+ par Adam Ondra en 2011.'),
(8, 'Charlotte', 'Durif', 'J’ai commencé l’escalade par la haute montagne avec mon frère et mon père dans les massifs de l’Oisans et du Mont Blanc, sur des voies de plusieurs longueurs, avec parfois un bivouac sur glacier. Puis vers 9 ans, j’ai découvert l’escalade indoor sur résine. Dans le même temps, je n’ai pas quitté le milieu naturel, mais c’est vers les falaises sportives, sans rien lacher des grandes voies, que se sont enrichies mes motivations. Ainsi, je passais la nuit anniversaire de mes 12 ans à suivre les positions de la Grande Ourse en bivouaquant en paroi dans happy birthday à la croix des têtes, sympa little Bigwall de Maurienne.\r\nMes terrains favoris sont les grandes longueurs de 40 à 70m. Elles sont des voyages sans fin. Elles me donnent le temps de grimper, de prendre du plaisir et de me resservir les plats. Chaque section de chaque voie est une découverte. J’aime décrypter un passage, imaginer sa résolution et ressentir une forme de créativité. Je me suis donc inscrite depuis mes débuts dans une filière de conti.\r\nSi jusqu’à 8a+, l’escalade m’était encore très intuitive, je me suis adaptée moins spontanément aux représentations de la haute difficulté. Il m’aura fallu accepter le principe du travail de voies impliquant des gestuelles plus violentes. Cette étape de ma progression n’est pas la plus simple. En tant que féminine, ce n’est pas sans une sérieuse volonté que d’aller contre ma nature plus féline.\r\nJ’ai eu l’opportunité d’aborder cet investissement dans le Tarn et la Dourbie, accompagnée d’un bon copain, dont la manière de grimper aura su éveiller l’attention qui m’était nécessaire pour aller un peu plus loin. A présent, l’intensité et la richesse de ces voies est tellement excessive qu’il m’en reste une très forte émotion, suffisante à mon investissement et ma sensibilité.\r\n\r\n'),
(9, 'Junko', 'Tabei', 'Junko Tabei était plutôt une alpiniste, et non une grimpeuse… Ce qui ne l’a pas empêché de se démarquer, bien avant que Lynn Hill ne monte la paroi d’El Capitan, en devenant la première femme à rallier le sommet de l’Everest en 1975. Enfant fragile, elle grandit à une époque où les stéréotypes de genre sont omniprésents et restrictifs. Elle devient malgré tout une pionnière de l’alpinisme et fonde en 1969 le “Climbing Club” car de nombreux hommes refusent de grimper avec elle.\r\nC’est avec une équipe entièrement composée de femmes japonaises qu’elle gravit pour la première fois le sommet de l’Everest (et échappe de peu à une avalanche mortelle). “Je me fichais d’être la première femme à grimper l’Everest, j’ai juste gravi une montagne”, explique-telle. “C’est surtout l’environnement autour de moi qui a énormément changé car j’étais la première femme”.\r\nEn 1992, soit un an avant que Lynn Hill ne grimpe The Nose, Tabei coche le dernier des Sept Sommets (de la liste de Messner), et devient définitivement l’une des plus grandes alpinistes de l’histoire.'),
(10, 'Lynn', 'Hill', 'Pionnière de l’escalade dans les années 1980 et 1990, Lynn Hill est la première femme à réellement marquer les grands murs de son empreinte. Et quelle empreinte ! Elle est la première à monter The Nose, situé sur El Capitan.\r\n“Je ne me souviens pas avoir reculé devant quelconque ascension. J’ai toujours essayé de m’aventurer sur des chemins qui requièrent de prendre des risques”.\r\nHill n’a que 14 ans quand elle se met à la pratique de l’escalade et il ne lui faut que 4 ans pour réussir la voie la plus difficile réalisée par une femme, l’Ophir Broke dans le Colorado, notée 7c (5.12d). En 1993, elle grimpe The Nose, en 4 jours et réussit l’exploit de le faire en une seule journée une année plus tard. Ces ascensions en font une star planétaire et lui permettent notamment d’apparaître dans le magazine Sports Illustrated et dans l’émission de David Letterman aux États-Unis.'),
(11, 'Beth', 'Rodden', 'Beth Rodden a commencé à se faire un nom sur la scène de l’escalade de grosses parois à Yosemite dans les années 1990 et est par la suite devenue l\'une des rockstars de la grimpe.\r\nÀ l’origine plus tournée vers l’escalade de compétition, elle se met à l’outdoor après un passage au Parc d’État de Smith Rock, dans l’Oregon. Elle y rencontre alors Lynn Hill et gravit la voie “To Bolt or not to Be”. Hill détecte son potentiel et l’invite à la rejoindre pour grimper à Madagascar. Une fois de retour aux États-Unis, elle revient sur les murs de Yosemite et rencontre Tommy Caldwell, un autre prodige de l’escalade, avec qui elle forme le couple le plus connu de la discipline.\r\nEn 2000, ils sont les premiers à emprunter la voie Lurking Fear sur El Capitan mais, après un enlèvement au Kyrgyzstan, ils s’éloignent pendant un an du monde de l’escalade. En 2005, ils deviennent, après Lynn Hill, les deuxièmes et troisièmes à grimper The Nose sans assistance.\r\n“Escalader The Nose était le rêve d’une vie”, déclare-t-elle. “J’ai commencé l’escalade l’année où Lynn l’a fait. Dans toutes les compétitions, toutes les salles de sport où j’allais, j’avais un poster d’elle qui disait “C’est parti, les gars”. Avant même de connaître El Capitan, je me disais “Oh, je veux être comme elle”.\r\nEn 2008, Rodden emprunte la voie la plus difficile de Yosemite (8c+ / 5.14c), une performance inédite, même Ron Kauk. Renommée Meltdown, cette voie n’a jamais été grimpée depuis. Pour plus d’informations sur Beth Rodden, allez voir ses liens particuliers avec Tommy Caldwell et sa tentative d’ascension du Dawn Wall.'),
(12, 'Sasha', 'DiGiulian', 'Souvent décrite comme l’une des meilleures grimpeuses au monde du moment, Sasha DiGiulian a plus de 30 premières ascensions féminines à son actif et 8 premières ascensions notables.\r\nInspirée par Lynn Hill, elle commence l’escalade à l’âge de 8 ans et devient à 18 la troisième femme, après l’Espagnole Josune Bereziartu et la Française Charlotte Durif à escalader une voie 9a (5.14d) dans les gorges de la Red River au Kentucky.\r\n“Les premières ascensions, notamment féminines, sont des moments historiques de notre sport”, explique-t-elle. “Clairement, ce serait idéal que les femmes puissent faire plus de premières ascensions”.'),
(26, 'Claire', 'Buhrfeind', 'Cette grimpeuse n’a que 21 ans mais son CV est déjà bien rempli. Après une blessure qui l\'a privé de saison hivernale, la quadruple championne de l’US Open National est revenue dans le game en travaillant d’arrache-pied pour obtenir sa place dans l’équipe nationale américaine.'),
(24, 'Shauna', 'Coxsey', 'Shauna Coxsey est la meilleure grimpeuse de l’histoire de la Grande-Bretagne. Et elle continue d’agrandir son palmarès avec une médaille de bronze acquise lors des championnats du monde d\'escalade de 2019 sur l’épreuve du combiné.'),
(25, 'Alex', 'Megos', 'À 23 ans, Alex Megos est l’un des alpinistes les plus connus de la planète. Si l’Allemand a déjà remporté plusieurs titres prestigieux (il a terminé vice-champion d’Europe de bloc en 2017, ndlr), il s’est progressivement dirigé vers l’escalade en plein air. Megos est la première personne à avoir réussi une voie à vue en 9a. Ce mode d’escalade est considéré comme le plus difficile car il consiste à grimper et réussir une voie du premier essai, sans repérages.'),
(22, 'Ashima ', 'Shiraishi', 'Plus jeune de sa génération, Ashima Shiraishi a réalisé à seulement 13 ans la deuxième ascension féminine d\'une voie 9a/9a+ (5.15d/5.15a). Elle est, à l’heure actuelle, considérée comme la meilleure jeune grimpeuse du monde.\r\nSon histoire avec l’escalade débute lorsqu’elle a six ans à Central Park, sur le Rat Rock, avec son père. Rapidement, son talent exceptionnel lui permet de devenir la plus jeune grimpeuse à réussir une voie notée 8c+ (5.14c) dans les gorges de la Red River.\r\n“J’ai toujours estimé que j’avais la même force que les garçons et je savais que j’étais capable de leur montrer”, explique Shiraishi. “C’est aussi ça, la beauté de l’escalade, on peut grimper n’importe quel type de voie et les filles peuvent montrer qu’elles déchirent à ça”.\r\nEn 2015, Shiraishi grimpe sa première 9a (5.14d) à l’Open Your Mind Direct. Durant la même année, elle franchit un cap en devenant la deuxième femme à escalader une voie 9a/9a+ (5.14d/5.15a) à Ciudad de Dios… Et nul doute qu’un jour elle sera la première à faire gagner quelques niveaux encore à la barre de l’escalade.'),
(23, 'Adam', 'Ondra', 'Reconnu comme l’un des meilleurs grimpeurs de l’histoire, Adam Ondra a déjà tout conquis. C’est lui qui a gravi le premier des voies en 9b et 9c. Il a déjà remporté plusieurs médailles d’or et d’argent en Coupe du Monde sur les trois spécialités (difficulté, vitesse et bloc). Regardez comment le Tchèque s’y prend pour devenir le meilleur au monde dans la cinquième saison de \"Reel Rock\".'),
(21, 'Angela', 'Eiter', 'La féroce compétitrice Angela Eiter se retrouve sur le devant de la scène en 2017 lorsqu’elle devient la première femme à grimper une voie notée 9b (5.15) sur la Plata de Shiva. Un niveau de difficulté seulement dépassé par les deux grimpeurs Adam Ondra et Chris Sharma.\r\n“Je suis très fière que les femmes cassent les codes et repoussent leurs limites toujours plus loin”, affirme-t-elle. “Il y a tellement d\'athlètes féminines impressionnantes dont on peut s\'inspirer, et tellement de nouvelles qui font maintenant des ascensions révolutionnaires.\" Angela débute l’escalade à l’âge de 11 ans, remporte son premier titre mondial à 17 ans et escalade sa première voie 8c+ (5.14d) en 2014, Claudio Café, à peine âgée de 21 ans. En 2014, elle élève encore plus son niveau et termine Hades et Big Hammer, deux voies 9a (5.14d) situées dans son Autriche natale. Elle réitère l’exploit sur l’Era Vella en Espagne l’année suivante, durant sa préparation pour la Planta de Shiva.'),
(19, 'Margo', 'Hayes', 'En étant la première femme à escalader La Rambla en février 2017, une voie située en Espagne notée 9a+ (5.15), Margo Hayes a mis la barre très haute. Son record a tenu 9 mois avant d’être battu par Angela Eiter avec une hauteur cotée à 9b (5.15b).\r\nHayes découvre l’escalade à l’âge de 10 ans avec l’équipe ABC de Boulder (Colorado) après avoir fait de la gymnastique à un niveau national. Durant l’année qui la mène à la performance de la Rambla, elle en profite pour escalader des voies notées 5.14 et plus.\r\n“Quand je me suis attachée à la paroi de la Rambla, j’ai été surprise par le flot d\'émotions\", dit-elle. “J’ai tout de suite commencé à pleurer. Je pense que c’était un mélange de joie et d’incrédulité. Je n’oublierai jamais ce moment”.\r\nPour dompter la Rambla, Margo Hayes a étalé ses 17 tentatives sur 7 jours. Une fois le mur gravi, elle s’est lancée dans l’écriture de son autobiographie.'),
(20, 'Janja', 'Garnbret', 'Si elle est avant tout une grimpeuse de compétition, Janja Garnbret a marqué l’outdoor de son empreinte en escaladant les 360 mètres de la tour de la station électrique de Trbovlje aux côtés de son compatriote Domen Skofic.\r\nDepuis qu’elle s’est éloignée du circuit des championnats du monde IFSC, le potentiel de Janja semble presque illimité. Après tout, elle est la seule grimpeuse à être restée invaincue sur toute la durée d’une saison et a semblé intouchable aux JO de Tokyo lorsqu’elle a remporté la première médaille d’or de l’histoire de son sport.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
